name: ultranet_cctv_scanner_mobile
description: Mobile CCTV discovery, diagnostics and live-view toolkit.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^11.2.0
  flutter_vlc_player: ^7.4.4
  network_info_plus: ^8.2.1
  path_provider: ^2.1.6
  pdf: ^3.13.1
  share_plus: ^13.3.0
  shared_preferences: ^2.5.5
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
